### PR TITLE
Update for JupyterLab 0.31

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Comment by IamGianluca** [comment]
First of all, thanks for your hard work guys! 

Is there a timeline for when this PR is going to be merged and a new release deployed? At my company, we would like to use `jupyterlab_bokeh` with `jupyterlab==0.31.1`.

**Comment by canavandl** [comment]
tested with bokeh=0.12.3 and jlab=0.31 and things LGTM

screen shot 2018-01-13 at 4 12 05 pm

**Comment by canavandl** [comment]
@IamGianluca this PR has been merged and a new version of this extension has been published. Please let us know if you have any issues.

**Comment by IamGianluca** [comment]
Hi @canavandl . I'm having some troubles installing it due to `jupyterlab` not recognizing my installation of `nodejs` and `npm`. I've tried to install it both on my main OS (Ubuntu 16.04 LTS) and python virtual environment (`pyenv` and `pyenv-virtualenvwrapper`), but for some reason, `jupyterlab` doesn't recognize them. I'm going to open an issue in `jupyterlab`.

**Pull request merged**
