### PR TITLE
Update dependencies, version, Lab->FrontEnd

### PR DESCRIPTION
**Pull request by athornton**
Sorry about the whitespace changes; I didn't notice those on my commit.

This updates dependencies and syntax for JL 1.0.0-alpha.6.

### CODE REVIEW

**Comment by stonebig** [comment]
any progress ? jupyterlab-1.0.0 release party is today

**Comment by juliusvonkohout** [comment]
> any progress ? jupyterlab-1.0.0 release party is today

I guess @bryevdv and @canavandl  have commit rights.

**Comment by bryevdv** [comment]
Sorry I didn't see any earlier emails of messages about this. I will try to test it out and merge tonight. I am not sure how the release is actually done @canavandl can hopefully chime in

**Comment by bryevdv** [comment]
OK I tested with JLab 1.0: basic, push_notebook, and embedded server. 

The push_notebook worked generally well, but was slightly flaky especially with the Number example. The notebook server embed had a consistent issue where nothing would display on the first call to `show`, but things would work if `show` was called again. 

@stonebig @athornton @canavandl anyone want to look in to these issues?  (particularly the second)

**Comment by stonebig** [comment]
@bryevdv I can only test published things. Can you push it to npm  as @next ?

**Comment by bryevdv** [comment]
@stonebig if you clone the repo there are instructions to run locally in the README

**Comment by athornton** [comment]
Like @stonebig, it's difficult for me to test this standalone (I have a Kubernetes installation, and the JL containers are built in such a way that users running notebooks do not have access to do much of anything outside their home directories.)  Publishing an rc-tagged candidate to NPM as @next would make it a great deal easier to test.

**Comment by bryevdv** [comment]
I don't personally know how to do that, unfortunately. If you can suggest how to publish a pre-release to NPM I can give it a shot.

**Comment by athornton** [comment]
If you have credentials to publish to npm, you just add `--tag next`.

So:
`npm login`
followed by
`npm publish --tag next`
(assuming you're sitting in the top-level directory of the NPM project; otherwise you can do `npm publish /path/to/package`)

Basically, *any* tag that is not `latest` will do, if you prefer `beta` or `rc` or whatever.  `next` seems to be a pretty common convention.

**Comment by bryevdv** [comment]
@athornton @stonebig I believe this is done
```
(base) ❯ npm publish --tag next

> jupyterlab_bokeh@1.0.0 prepack .
> npm run clean && npm run build


> jupyterlab_bokeh@1.0.0 clean /Users/bryan/work/jupyterlab_bokeh
> rimraf lib


> jupyterlab_bokeh@1.0.0 build /Users/bryan/work/jupyterlab_bokeh
> tsc

npm notice
npm notice 📦  jupyterlab_bokeh@1.0.0
npm notice === Tarball Contents ===
npm notice 1.2kB package.json
npm notice 1.5kB LICENSE.txt
npm notice 2.4kB README.md
npm notice 64B   lib/index.d.ts
npm notice 151B  lib/index.js
npm notice 540B  lib/manager.d.ts
npm notice 974B  lib/manager.js
npm notice 587B  lib/plugin.d.ts
npm notice 1.7kB lib/plugin.js
npm notice 1.4kB lib/renderer.d.ts
npm notice 5.0kB lib/renderer.js
npm notice === Tarball Details ===
npm notice name:          jupyterlab_bokeh
npm notice version:       1.0.0
npm notice package size:  5.1 kB
npm notice unpacked size: 15.4 kB
npm notice shasum:        718fde8e0d4fabf2233b0f53116654bcf256e713
npm notice integrity:     sha512-DahsavfoFdK+f[...]OgIpXJci9oB3Q==
npm notice total files:   11
npm notice
+ jupyterlab_bokeh@1.0.0
```

**Comment by bryevdv** [comment]
I'm not sure offhand that this version should have been "1.0" tho I am also not sure where the previous 0.6.x came from

**Comment by canavandl** [comment]
1.0 is fine. I've done an awful job of versioning this extension previously :)

Thanks @athornton for doing the update. It's super helpful

**Comment by bryevdv** [comment]
As @canavandl mentioned offline, we should just go ahead an merge this and do any follow on in a new PR.

**Pull request merged**
