### PR TITLE
Update for JL 0.32

### PR DESCRIPTION
**Pull request by athornton**

### CODE REVIEW

**Comment by athornton** [comment]
Please don't merge it yet.  Although it builds fine with the newer dependencies, it fails to load.

**Comment by athornton** [comment]
The problem was not in the code, but in my construction of my Lab container.  The patch appears to work correctly with the dependency update to the newer versions present in JL 0.32.

**Comment by athornton** [comment]
@canavandl wanted to make sure you were aware of this....

**Comment by philippjfr** [comment]
This PR will also require updates to the Comm handling since they were made asynchronous in: https://github.com/jupyterlab/jupyterlab/pull/4115. Would you be willing to take this on or should I open a separate PR once this has been merged? I had to make the same changes in https://github.com/pyviz/jupyterlab_holoviews/commit/4a17ca10e594adec55054a3c92908c5bb06e2d66

**Comment by philippjfr** [comment]
Nevermind I think the way jupyterlab_bokeh registers the Comm is actually fine.

**Comment by canavandl** [comment]
@philippjfr the Bokeh basic notebook comms example (https://github.com/bokeh/bokeh/blob/master/examples/howto/notebook_comms/Basic%20Usage.ipynb) doesn't work for me - it appears the comm isn't being registered. Do you have time to look at it?

**Comment by jochym** [comment]
The problem from https://github.com/bokeh/jupyterlab_bokeh/issues/33 persists since the upper bound is (apparently) automatically set to next semantic version:
```
"jupyterlab_bokeh@0.4.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.16.2 <0.17.0        >=0.15.0 <0.16.0 @jupyterlab/application
>=0.16.3 <0.17.0        >=0.15.4 <0.16.0 @jupyterlab/apputils
>=0.16.2 <0.17.0        >=0.15.0 <0.16.0 @jupyterlab/notebook
>=2.0.2 <3.0.0          >=1.0.1 <2.0.0   @jupyterlab/services
```

**Comment by philippjfr** [comment]
>Do you have time to look at it?

I'll have a look, can't quite see what is wrong since HoloViews uses very similar code.

**Comment by canavandl** [comment]
superceded by #37 

Thanks for the PR and ping @jochym ! I ended branching your PR to rebase because I'm going to be ATF on vacation and wanted to get a release out ASAP.

**Pull request closed without merging**
